name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o truto-mcp-stdio-linux-amd64-v${{ github.ref_name }}
          GOOS=darwin GOARCH=amd64 go build -o truto-mcp-stdio-darwin-amd64-v${{ github.ref_name }}
          GOOS=darwin GOARCH=arm64 go build -o truto-mcp-stdio-darwin-arm64-v${{ github.ref_name }}
          GOOS=windows GOARCH=amd64 go build -o truto-mcp-stdio-windows-amd64-v${{ github.ref_name }}.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            truto-mcp-stdio-linux-amd64-v${{ github.ref_name }}
            truto-mcp-stdio-darwin-amd64-v${{ github.ref_name }}
            truto-mcp-stdio-darwin-arm64-v${{ github.ref_name }}
            truto-mcp-stdio-windows-amd64-v${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 